apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
    env: dev
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis  # has to match .spec.template.metadata.labels
      env: dev
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis  # has to match .spec.selector.matchLabels
        env: dev
    spec:
      containers:
        - name: redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)"]
          ports:
            - containerPort: 6379
              name: redis
          env:
#            - name: REDIS_PASS
#              value: "youpass"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: REDIS_PASS
